/* Generated By:JavaCC: Do not edit this line. NuevoParserConstants.java */
package uniandes.teolen.parserJavaCC.newParser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface NuevoParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ORIENTATION = 5;
  /** RegularExpression Id. */
  int DIRECTION = 6;
  /** RegularExpression Id. */
  int VIEW = 7;
  /** RegularExpression Id. */
  int AROUND = 8;
  /** RegularExpression Id. */
  int LEFT = 9;
  /** RegularExpression Id. */
  int RIGHT = 10;
  /** RegularExpression Id. */
  int BACK = 11;
  /** RegularExpression Id. */
  int NORTH = 12;
  /** RegularExpression Id. */
  int SOUTH = 13;
  /** RegularExpression Id. */
  int EAST = 14;
  /** RegularExpression Id. */
  int WEST = 15;
  /** RegularExpression Id. */
  int FRONT = 16;
  /** RegularExpression Id. */
  int MOV = 17;
  /** RegularExpression Id. */
  int PUT = 18;
  /** RegularExpression Id. */
  int PICK = 19;
  /** RegularExpression Id. */
  int POP = 20;
  /** RegularExpression Id. */
  int GO = 21;
  /** RegularExpression Id. */
  int HOP = 22;
  /** RegularExpression Id. */
  int FACING = 23;
  /** RegularExpression Id. */
  int CANPUT = 24;
  /** RegularExpression Id. */
  int CANPICK = 25;
  /** RegularExpression Id. */
  int CANMOVEINDIR = 26;
  /** RegularExpression Id. */
  int CANJUMPINDIR = 27;
  /** RegularExpression Id. */
  int CANMOVETOTHE = 28;
  /** RegularExpression Id. */
  int CANJUMPTOTHE = 29;
  /** RegularExpression Id. */
  int NOT = 30;
  /** RegularExpression Id. */
  int ASSIGNTO = 31;
  /** RegularExpression Id. */
  int GOTO = 32;
  /** RegularExpression Id. */
  int MOVE = 33;
  /** RegularExpression Id. */
  int TURN = 34;
  /** RegularExpression Id. */
  int FACE = 35;
  /** RegularExpression Id. */
  int MOVETOTHE = 36;
  /** RegularExpression Id. */
  int JUMPTOTHE = 37;
  /** RegularExpression Id. */
  int MOVEINDIR = 38;
  /** RegularExpression Id. */
  int JUMPINDIR = 39;
  /** RegularExpression Id. */
  int NOP = 40;
  /** RegularExpression Id. */
  int ITEM = 41;
  /** RegularExpression Id. */
  int BALLOONS = 42;
  /** RegularExpression Id. */
  int CHIPS = 43;
  /** RegularExpression Id. */
  int NUM = 44;
  /** RegularExpression Id. */
  int DIGIT = 45;
  /** RegularExpression Id. */
  int ROBOT_R = 46;
  /** RegularExpression Id. */
  int THEN = 47;
  /** RegularExpression Id. */
  int ELSE = 48;
  /** RegularExpression Id. */
  int DO = 49;
  /** RegularExpression Id. */
  int VARS = 50;
  /** RegularExpression Id. */
  int PROCS = 51;
  /** RegularExpression Id. */
  int WHILE = 52;
  /** RegularExpression Id. */
  int IF = 53;
  /** RegularExpression Id. */
  int REPEAT = 54;
  /** RegularExpression Id. */
  int NAME = 55;
  /** RegularExpression Id. */
  int LETTER = 56;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<ORIENTATION>",
    "<DIRECTION>",
    "<VIEW>",
    "\"around\"",
    "\"left\"",
    "\"right\"",
    "\"back\"",
    "\"north\"",
    "\"south\"",
    "\"east\"",
    "\"west\"",
    "\"front\"",
    "\"Mov\"",
    "\"Put\"",
    "\"Pick\"",
    "\"Pop\"",
    "\"GO\"",
    "\"HOP\"",
    "\"facing\"",
    "\"canput\"",
    "\"canpick\"",
    "\"canmoveindir\"",
    "\"canjumpindir\"",
    "\"canmovetothe\"",
    "\"canjumptothe\"",
    "\"not\"",
    "\"assignto\"",
    "\"goto\"",
    "\"move\"",
    "\"turn\"",
    "\"face\"",
    "\"movetothe\"",
    "\"jumptothe\"",
    "\"moveindir\"",
    "\"jumpindir\"",
    "\"nop\"",
    "<ITEM>",
    "\"balloons\"",
    "\"chips\"",
    "<NUM>",
    "<DIGIT>",
    "\"robot_r\"",
    "\"then\"",
    "\"else\"",
    "\"do\"",
    "\"vars\"",
    "\"procs\"",
    "\"while\"",
    "\"if\"",
    "\"repeat\"",
    "<NAME>",
    "<LETTER>",
    "\",\"",
    "\";\"",
    "\"[\"",
    "\"|\"",
    "\"]\"",
    "\":\"",
  };

}
