/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MOV = 5;
  /** RegularExpression Id. */
  int RIGHT = 6;
  /** RegularExpression Id. */
  int PUT = 7;
  /** RegularExpression Id. */
  int PICK = 8;
  /** RegularExpression Id. */
  int POP = 9;
  /** RegularExpression Id. */
  int GO = 10;
  /** RegularExpression Id. */
  int HOP = 11;
  /** RegularExpression Id. */
  int BALLOONS = 12;
  /** RegularExpression Id. */
  int CHIPS = 13;
  /** RegularExpression Id. */
  int NUM = 14;
  /** RegularExpression Id. */
  int DIGIT = 15;
  /** RegularExpression Id. */
  int ORIENTATION = 17;
  /** RegularExpression Id. */
  int LEFT = 18;
  /** RegularExpression Id. */
  int VIEW = 19;
  /** RegularExpression Id. */
  int AROUND = 20;
  /** RegularExpression Id. */
  int BACK = 21;
  /** RegularExpression Id. */
  int NORTH = 22;
  /** RegularExpression Id. */
  int SOUTH = 23;
  /** RegularExpression Id. */
  int EAST = 24;
  /** RegularExpression Id. */
  int WEST = 25;
  /** RegularExpression Id. */
  int FRONT = 26;
  /** RegularExpression Id. */
  int FACING = 27;
  /** RegularExpression Id. */
  int CANPUT = 28;
  /** RegularExpression Id. */
  int CANPICK = 29;
  /** RegularExpression Id. */
  int CANMOVEINDIR = 30;
  /** RegularExpression Id. */
  int CANJUMPINDIR = 31;
  /** RegularExpression Id. */
  int CANMOVETOTHE = 32;
  /** RegularExpression Id. */
  int CANJUMPTOTHE = 33;
  /** RegularExpression Id. */
  int NOT = 34;
  /** RegularExpression Id. */
  int ASSIGNTO = 35;
  /** RegularExpression Id. */
  int GOTO = 36;
  /** RegularExpression Id. */
  int MOVE = 37;
  /** RegularExpression Id. */
  int TURN = 38;
  /** RegularExpression Id. */
  int FACE = 39;
  /** RegularExpression Id. */
  int MOVETOTHE = 40;
  /** RegularExpression Id. */
  int JUMPTOTHE = 41;
  /** RegularExpression Id. */
  int MOVEINDIR = 42;
  /** RegularExpression Id. */
  int JUMPINDIR = 43;
  /** RegularExpression Id. */
  int NOP = 44;
  /** RegularExpression Id. */
  int ROBOT_R = 45;
  /** RegularExpression Id. */
  int THEN = 46;
  /** RegularExpression Id. */
  int ELSE = 47;
  /** RegularExpression Id. */
  int DO = 48;
  /** RegularExpression Id. */
  int VARS = 49;
  /** RegularExpression Id. */
  int PROCS = 50;
  /** RegularExpression Id. */
  int WHILE = 51;
  /** RegularExpression Id. */
  int IF = 52;
  /** RegularExpression Id. */
  int REPEAT = 53;
  /** RegularExpression Id. */
  int NAME = 54;
  /** RegularExpression Id. */
  int LETTER = 55;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"Mov\"",
    "\"RIGHT\"",
    "\"Put\"",
    "\"Pick\"",
    "\"Pop\"",
    "\"GO\"",
    "\"HOP\"",
    "\"BALLOONS\"",
    "\"CHIPS\"",
    "<NUM>",
    "<DIGIT>",
    "\",\"",
    "<ORIENTATION>",
    "\"left\"",
    "<VIEW>",
    "\"around\"",
    "\"back\"",
    "\"north\"",
    "\"south\"",
    "\"east\"",
    "\"west\"",
    "\"front\"",
    "\"facing\"",
    "\"canput\"",
    "\"canpick\"",
    "\"canmoveindir\"",
    "\"canjumpindir\"",
    "\"canmovetothe\"",
    "\"canjumptothe\"",
    "\"not\"",
    "\"assignto\"",
    "\"goto\"",
    "\"move\"",
    "\"turn\"",
    "\"face\"",
    "\"movetothe\"",
    "\"jumptothe\"",
    "\"moveindir\"",
    "\"jumpindir\"",
    "\"nop\"",
    "\"robot_r\"",
    "\"then\"",
    "\"else\"",
    "\"do\"",
    "\"vars\"",
    "\"procs\"",
    "\"while\"",
    "\"if\"",
    "\"repeat\"",
    "<NAME>",
    "<LETTER>",
    "\";\"",
    "\"[\"",
    "\"|\"",
    "\"]\"",
    "\":\"",
  };

}
