/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MOV = 5;
  /** RegularExpression Id. */
  int RIGHT = 6;
  /** RegularExpression Id. */
  int PUT = 7;
  /** RegularExpression Id. */
  int PICK = 8;
  /** RegularExpression Id. */
  int POP = 9;
  /** RegularExpression Id. */
  int GO = 10;
  /** RegularExpression Id. */
  int HOP = 11;
  /** RegularExpression Id. */
  int BALLOONS = 12;
  /** RegularExpression Id. */
  int CHIPS = 13;
  /** RegularExpression Id. */
  int NUM = 14;
  /** RegularExpression Id. */
  int DIGIT = 15;
  /** RegularExpression Id. */
  int ROBOT_R = 16;
  /** RegularExpression Id. */
  int THEN = 17;
  /** RegularExpression Id. */
  int ELSE = 18;
  /** RegularExpression Id. */
  int DO = 19;
  /** RegularExpression Id. */
  int VARS = 20;
  /** RegularExpression Id. */
  int PROCS = 21;
  /** RegularExpression Id. */
  int WHILE = 22;
  /** RegularExpression Id. */
  int IF = 23;
  /** RegularExpression Id. */
  int REPEAT = 24;
  /** RegularExpression Id. */
  int NAME = 25;
  /** RegularExpression Id. */
  int LETTER = 26;
  /** RegularExpression Id. */
  int ORIENTATION = 27;
  /** RegularExpression Id. */
  int VIEW = 28;
  /** RegularExpression Id. */
  int TURN = 29;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"Mov\"",
    "\"RIGHT\"",
    "\"Put\"",
    "\"Pick\"",
    "\"Pop\"",
    "\"GO\"",
    "\"HOP\"",
    "\"BALLOONS\"",
    "\"CHIPS\"",
    "<NUM>",
    "<DIGIT>",
    "\"robot_r\"",
    "\"then:\"",
    "\"else:\"",
    "\"do:\"",
    "\"vars\"",
    "\"procs\"",
    "\"while:\"",
    "\"if:\"",
    "\"repeat:\"",
    "<NAME>",
    "<LETTER>",
    "<ORIENTATION>",
    "<VIEW>",
    "<TURN>",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\";\"",
    "\"[\"",
    "\"|\"",
    "\"]\"",
    "\":\"",
    "\"assignto:\"",
    "\"goto:\"",
    "\"move:\"",
    "\"turn:\"",
    "\"face:\"",
    "\"put:\"",
    "\"pick:\"",
    "\"movetothe:\"",
    "\"moveindir:\"",
    "\"jumptothe:\"",
    "\"jumpindir:\"",
    "\"facing:\"",
    "\"canPut:\"",
    "\"canPick:\"",
    "\"canMoveInDir:\"",
    "\"canJumpInDir:\"",
    "\"canMoveToThe:\"",
    "\"canJumpToThe:\"",
    "\"not:\"",
  };

}
