/* Generated By:JavaCC: Do not edit this line. Robot.java */
package uniandes.lym.robot.control;

import uniandes.lym.robot.kernel.*;
import uniandes.lym.robot.view.Console;

import java.awt.Point;
import java.io.*;
import java.util.Vector;
import java.util.LinkedList;
import java.util.HashMap;
import java.util.HashSet;

@SuppressWarnings("serial")
public class Robot implements RobotConstants {


        private RobotWorldDec world;


        void setWorld(RobotWorld w) {
                world = (RobotWorldDec) w;
        }

        String salida=new String();

        //boolean command(uniandes.lym.robot.view.Console sistema) :
  final public boolean command(Console sistema) throws ParseException {
                int x,y;
                salida=new String();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MOV:
    case RIGHT:
    case PUT:
    case PICK:
    case POP:
    case GO:
    case HOP:
      label_1:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case RIGHT:
          jj_consume_token(RIGHT);
          jj_consume_token(5);
          jj_consume_token(6);
                                    world.turnRight();salida = "Command: Turnright";
          break;
        case MOV:
          jj_consume_token(MOV);
          jj_consume_token(5);
          x = num();
          jj_consume_token(6);
                                                world.moveForward(x,false);salida = "Command: Moveforward ";
          break;
        case HOP:
          jj_consume_token(HOP);
          jj_consume_token(5);
          x = num();
          jj_consume_token(6);
                                                world.moveForward(x,true);salida = "Command:Jumpforward ";
          break;
        case GO:
          jj_consume_token(GO);
          jj_consume_token(5);
          x = num();
          jj_consume_token(7);
          y = num();
          jj_consume_token(6);
                                                          world.setPostion(x,y);salida = "Command:GO ";
          break;
        case PUT:
          jj_consume_token(PUT);
          jj_consume_token(5);
          put();
          jj_consume_token(6);
          break;
        case PICK:
          jj_consume_token(PICK);
          jj_consume_token(5);
          get();
          jj_consume_token(6);
          break;
        case POP:
          jj_consume_token(POP);
          jj_consume_token(5);
          x = num();
          jj_consume_token(6);
                                        world.popBalloons(x); salida = "Comando:  Pop";
          break;
        default:
          jj_la1[0] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        jj_consume_token(8);
                    try {
                                 Thread.sleep(900);
                    } catch (InterruptedException e) {
                                        System.err.format("IOException: %s%n", e);
                            }

                        sistema.printOutput(salida);
                        {if (true) return true;}
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case MOV:
        case RIGHT:
        case PUT:
        case PICK:
        case POP:
        case GO:
        case HOP:
          ;
          break;
        default:
          jj_la1[1] = jj_gen;
          break label_1;
        }
      }
      break;
    case 0:
      jj_consume_token(0);
                 {if (true) return false;}
      break;
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public void put() throws ParseException {
                int f=1;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case CHIPS:
      jj_consume_token(CHIPS);
      jj_consume_token(7);
      f = num();
                                          world.putChips(f); salida = "Command:  Put Chips";
      break;
    case BALLOONS:
      jj_consume_token(BALLOONS);
      jj_consume_token(7);
      f = num();
                                                      world.putBalloons(f); salida = "Command:  Put Balloons";
      break;
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void get() throws ParseException {
                int f=1;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case CHIPS:
      jj_consume_token(CHIPS);
      jj_consume_token(7);
      f = num();
                                         world.pickChips(f);salida = "Command:  Pick chips";
      break;
    case BALLOONS:
      jj_consume_token(BALLOONS);
      jj_consume_token(7);
      f = num();
                                                      world.grabBalloons(f);salida="Command:  Pick balloons";
      break;
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void main() throws ParseException {
    jj_consume_token(ROBOT_R);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case VARS:
      vars();
      break;
    default:
      jj_la1[5] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PROCS:
      procs();
      break;
    default:
      jj_la1[6] = jj_gen;
      ;
    }
    block();
  }

  final public void vars() throws ParseException {
 String var1, var2;
    jj_consume_token(VARS);
    var1 = jj_consume_token(NAME).image;
                                         token_source.variables.put(var1, "Undefined");
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 7:
        ;
        break;
      default:
        jj_la1[7] = jj_gen;
        break label_2;
      }
      jj_consume_token(7);
      var2 = jj_consume_token(NAME).image;
                                     token_source.variables.put(var2, "Undefined");
    }
    jj_consume_token(8);
  }

  final public void procs() throws ParseException {
    jj_consume_token(PROCS);
    label_3:
    while (true) {
      procDefinition();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NAME:
        ;
        break;
      default:
        jj_la1[8] = jj_gen;
        break label_3;
      }
    }
  }

  final public void procDefinition() throws ParseException {
 String procName;int cantidadParametros;
    //Funcion para crear procedimientos
    
      procName = jj_consume_token(NAME).image;
    jj_consume_token(59);
    jj_consume_token(60);
    cantidadParametros = parameters();
                                             saveProcInfo(procName.toLowerCase(), cantidadParametros);
    jj_consume_token(60);
    multipleExecution();
   token_source.variables_temporales = new HashMap < String,Integer > ();
    jj_consume_token(61);
  }

  final public int parameters() throws ParseException {
 String parameter1, parameter2;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NAME:
      parameter1 = jj_consume_token(NAME).image;
                                               token_source.variables_temporales.put(parameter1,0);
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 7:
          ;
          break;
        default:
          jj_la1[9] = jj_gen;
          break label_4;
        }
        jj_consume_token(7);
        parameter2 = jj_consume_token(NAME).image;
                                               token_source.variables_temporales.put(parameter2,0);
      }
      break;
    default:
      jj_la1[10] = jj_gen;
      ;
    }
           {if (true) return token_source.variables_temporales.size();}
    throw new Error("Missing return statement in function");
  }

  final public void saveProcInfo(String procName, int params) throws ParseException {
                        if (token_source.variables.containsKey(procName)){if (true) throw new Error("El procedimiento ya se declar\u00f3 como variable");}
                        else if (token_source.condiciones.contains(procName)){if (true) throw new Error("El procedimiento es una condici\u00f3n");}
                        else token_source.procedimientos.put(procName,params);
  }

  final public void block() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 59:
      jj_consume_token(59);
      multipleExecution();
      jj_consume_token(61);
      break;
    case PUT:
    case PICK:
    case ASSIGNTO:
    case GOTO:
    case MOVE:
    case TURN:
    case FACE:
    case MOVETOTHE:
    case JUMPTOTHE:
    case MOVEINDIR:
    case JUMPINDIR:
    case NOP:
    case WHILE:
    case IF:
    case REPEAT:
    case NAME:
      singleExecution();
      break;
    default:
      jj_la1[11] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void multipleExecution() throws ParseException {
    singleExecution();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 8:
        ;
        break;
      default:
        jj_la1[12] = jj_gen;
        break label_5;
      }
      jj_consume_token(8);
      singleExecution();
    }
  }

  final public void singleExecution() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case WHILE:
    case IF:
    case REPEAT:
      controlStructure();
      break;
    case PUT:
    case PICK:
    case ASSIGNTO:
    case GOTO:
    case MOVE:
    case TURN:
    case FACE:
    case MOVETOTHE:
    case JUMPTOTHE:
    case MOVEINDIR:
    case JUMPINDIR:
    case NOP:
      declaredProcedureCall();
      break;
    case NAME:
      procedureCall();
      break;
    default:
      jj_la1[13] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void procedureCall() throws ParseException {
 String procName;int cantidadParametros;
    /* 
    	  *Se llama un procedimiento del usuario
    	  *Se comprueba que el nombre este definido y tenga la cantidad justa de parametros
     	*/
              procName = jj_consume_token(NAME).image;
    jj_consume_token(62);
    cantidadParametros = declaredParameters();
            if (token_source.procedimientos.containsKey(procName.toLowerCase()) == false) {if (true) throw new Error("El procedimiento " + procName + " no esta definido " + token.beginLine);}
            else if (token_source.procedimientos.get(procName.toLowerCase()) != cantidadParametros) {if (true) throw new Error("Faltan o sobran parametros al llamar al procedimiento: " + procName);}
  }

  final public void controlStructure() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IF:
      IF();
      break;
    case WHILE:
      WHILE();
      break;
    case REPEAT:
      REPEAT();
      break;
    default:
      jj_la1[14] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public int declaredParameters() throws ParseException {
 int cantidad = 0;String parameter1, parameter2;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NUM:
    case NAME:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NAME:
        parameter1 = jj_consume_token(NAME).image;
                                        checkParameters(parameter1.toLowerCase());
        break;
      case NUM:
        parameter1 = jj_consume_token(NUM).image;
        break;
      default:
        jj_la1[15] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
                                                                                                                cantidad++;System.out.println(cantidad);
      label_6:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 7:
          ;
          break;
        default:
          jj_la1[16] = jj_gen;
          break label_6;
        }
        jj_consume_token(7);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case NAME:
          parameter2 = jj_consume_token(NAME).image;
                                           checkParameters(parameter2.toLowerCase());
          break;
        case NUM:
          parameter2 = jj_consume_token(NUM).image;
          break;
        default:
          jj_la1[17] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
                                                                                                                  cantidad++;
      }
      break;
    default:
      jj_la1[18] = jj_gen;
      ;
    }
         {if (true) return cantidad;}
    throw new Error("Missing return statement in function");
  }

  final public void checkParameters(String parameter) throws ParseException {
    //Se revisa si un parametro esta definido o si es variable
    if (token_source.variables.containsKey(parameter) == false &&
    token_source.variables_temporales.containsKey(parameter) == false) {if (true) throw new Error(parameter + " no esta definido" + token_source.variables_temporales);}
  }

  final public void IF() throws ParseException {
    jj_consume_token(IF);
    jj_consume_token(62);
    conditionalCall();
    jj_consume_token(THEN);
    jj_consume_token(62);
    block();
    jj_consume_token(ELSE);
    jj_consume_token(62);
    block();
  }

  final public void WHILE() throws ParseException {
    jj_consume_token(WHILE);
    jj_consume_token(62);
    conditionalCall();
    jj_consume_token(DO);
    jj_consume_token(62);
    block();
  }

  final public void REPEAT() throws ParseException {
 int num;
    jj_consume_token(REPEAT);
    jj_consume_token(62);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NUM:
      num = num();
      break;
    case NAME:
      num = getVarNum();
      break;
    default:
      jj_la1[19] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    block();
  }

  final public void declaredProcedureCall() throws ParseException {
 int n, Cx, Cy;String d, x, name, o;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ASSIGNTO:
      jj_consume_token(ASSIGNTO);
      jj_consume_token(62);
      n = num();
      jj_consume_token(7);
      name = jj_consume_token(NAME).image;
                   checkParameters(name.toLowerCase());
                   if (token_source.variables.containsKey(name)) token_source.variables.put(name, Integer.toString(n));
      break;
    case TURN:
      jj_consume_token(TURN);
      jj_consume_token(62);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AROUND:
        d = jj_consume_token(AROUND).image;
        break;
      case LEFT:
        d = jj_consume_token(LEFT).image;
        break;
      case RIGHT:
        d = jj_consume_token(RIGHT).image;
        break;
      default:
        jj_la1[20] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case FACE:
      jj_consume_token(FACE);
      jj_consume_token(62);
      o = jj_consume_token(ORIENTATION).image;
      break;
    case GOTO:
      jj_consume_token(GOTO);
      jj_consume_token(62);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NUM:
        Cx = num();
        break;
      case NAME:
        Cx = getVarNum();
        break;
      default:
        jj_la1[21] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(7);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NUM:
        Cy = num();
        break;
      case NAME:
        Cy = getVarNum();
        break;
      default:
        jj_la1[22] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case MOVE:
      jj_consume_token(MOVE);
      jj_consume_token(62);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NUM:
        n = num();
        break;
      case NAME:
        n = getVarNum();
        break;
      default:
        jj_la1[23] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case PUT:
      jj_consume_token(PUT);
      jj_consume_token(62);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NUM:
        n = num();
        break;
      case NAME:
        n = getVarNum();
        break;
      default:
        jj_la1[24] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(7);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case BALLOONS:
        x = jj_consume_token(BALLOONS).image;
        break;
      case CHIPS:
        x = jj_consume_token(CHIPS).image;
        break;
      default:
        jj_la1[25] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case PICK:
      jj_consume_token(PICK);
      jj_consume_token(62);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NUM:
        n = num();
        break;
      case NAME:
        n = getVarNum();
        break;
      default:
        jj_la1[26] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(7);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case BALLOONS:
        x = jj_consume_token(BALLOONS).image;
        break;
      case CHIPS:
        x = jj_consume_token(CHIPS).image;
        break;
      default:
        jj_la1[27] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case MOVETOTHE:
      jj_consume_token(MOVETOTHE);
      jj_consume_token(62);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NUM:
        n = num();
        break;
      case NAME:
        n = getVarNum();
        break;
      default:
        jj_la1[28] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(7);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VIEW:
        d = jj_consume_token(VIEW).image;
        break;
      case LEFT:
        d = jj_consume_token(LEFT).image;
        break;
      case RIGHT:
        d = jj_consume_token(RIGHT).image;
        break;
      default:
        jj_la1[29] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case MOVEINDIR:
      jj_consume_token(MOVEINDIR);
      jj_consume_token(62);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NUM:
        n = num();
        break;
      case NAME:
        n = getVarNum();
        break;
      default:
        jj_la1[30] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(7);
      d = jj_consume_token(ORIENTATION).image;
      break;
    case JUMPTOTHE:
      jj_consume_token(JUMPTOTHE);
      jj_consume_token(62);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NUM:
        n = num();
        break;
      case NAME:
        n = getVarNum();
        break;
      default:
        jj_la1[31] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(7);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VIEW:
        d = jj_consume_token(VIEW).image;
        break;
      case LEFT:
        d = jj_consume_token(LEFT).image;
        break;
      case RIGHT:
        d = jj_consume_token(RIGHT).image;
        break;
      default:
        jj_la1[32] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case JUMPINDIR:
      jj_consume_token(JUMPINDIR);
      jj_consume_token(62);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NUM:
        n = num();
        break;
      case NAME:
        n = getVarNum();
        break;
      default:
        jj_la1[33] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(7);
      d = jj_consume_token(ORIENTATION).image;
      break;
    case NOP:
      jj_consume_token(NOP);
      jj_consume_token(62);
      break;
    default:
      jj_la1[34] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void conditionalCall() throws ParseException {
 int n; String x,d,o;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case FACING:
      jj_consume_token(FACING);
      jj_consume_token(62);
      o = jj_consume_token(ORIENTATION).image;
      break;
    case CANPUT:
      jj_consume_token(CANPUT);
      jj_consume_token(62);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NUM:
        n = num();
        break;
      case NAME:
        n = getVarNum();
        break;
      default:
        jj_la1[35] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(7);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case BALLOONS:
        x = jj_consume_token(BALLOONS).image;
        break;
      case CHIPS:
        x = jj_consume_token(CHIPS).image;
        break;
      default:
        jj_la1[36] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case CANPICK:
      jj_consume_token(CANPICK);
      jj_consume_token(62);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NUM:
        n = num();
        break;
      case NAME:
        n = getVarNum();
        break;
      default:
        jj_la1[37] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(7);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case BALLOONS:
        x = jj_consume_token(BALLOONS).image;
        break;
      case CHIPS:
        x = jj_consume_token(CHIPS).image;
        break;
      default:
        jj_la1[38] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case CANMOVEINDIR:
      jj_consume_token(CANMOVEINDIR);
      jj_consume_token(62);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NUM:
        n = num();
        break;
      case NAME:
        n = getVarNum();
        break;
      default:
        jj_la1[39] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(7);
      d = jj_consume_token(ORIENTATION).image;
      break;
    case CANJUMPINDIR:
      jj_consume_token(CANJUMPINDIR);
      jj_consume_token(62);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NUM:
        n = num();
        break;
      case NAME:
        n = getVarNum();
        break;
      default:
        jj_la1[40] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(7);
      d = jj_consume_token(ORIENTATION).image;
      break;
    case CANMOVETOTHE:
      jj_consume_token(CANMOVETOTHE);
      jj_consume_token(62);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NUM:
        n = num();
        break;
      case NAME:
        n = getVarNum();
        break;
      default:
        jj_la1[41] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(7);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VIEW:
        o = jj_consume_token(VIEW).image;
        break;
      case LEFT:
        o = jj_consume_token(LEFT).image;
        break;
      case RIGHT:
        o = jj_consume_token(RIGHT).image;
        break;
      default:
        jj_la1[42] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case CANJUMPTOTHE:
      jj_consume_token(CANJUMPTOTHE);
      jj_consume_token(62);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NUM:
        n = num();
        break;
      case NAME:
        n = getVarNum();
        break;
      default:
        jj_la1[43] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(7);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VIEW:
        o = jj_consume_token(VIEW).image;
        break;
      case LEFT:
        o = jj_consume_token(LEFT).image;
        break;
      case RIGHT:
        o = jj_consume_token(RIGHT).image;
        break;
      default:
        jj_la1[44] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case NOT:
      jj_consume_token(NOT);
      jj_consume_token(62);
      conditionalCall();
      break;
    default:
      jj_la1[45] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public int num() throws ParseException, Error {
        int total = 1;
    jj_consume_token(NUM);
    try{
      total = Integer.parseInt(token.image);
      }
    catch (NumberFormatException ee){
      {if (true) throw new Error("No es posible convertir en numero: " + token.image + " !!");}
    }
    {if (true) return total;}
    throw new Error("Missing return statement in function");
  }

  final public int getVarNum() throws ParseException, Error {
 Token token;int number;
    token = jj_consume_token(NAME);
    //Se revisa si existe la variable
    checkParameters(token.image.toLowerCase());

    try{
          if (token_source.variables.containsKey(token.image.toLowerCase())) number = Integer.parseInt(token_source.variables.get(token.image.toLowerCase()));
          else number = token_source.variables_temporales.get(token.image.toLowerCase());
    }
    catch (NumberFormatException ee){
      {if (true) throw new Error("Variable con valor undefined" + token.beginLine + token_source.variables + token.image + token_source.variables_temporales);}
    }
    {if (true) return number;}
    throw new Error("Missing return statement in function");
  }

  /** Generated Token Manager. */
  public RobotTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[46];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0xfe00,0xfe00,0xfe01,0x0,0x0,0x0,0x0,0x80,0x0,0x80,0x0,0x1800,0x100,0x1800,0x0,0x0,0x80,0x0,0x0,0x0,0xa0400,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x60400,0x0,0x0,0x60400,0x0,0x1800,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x60400,0x0,0x60400,0xfc000000,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x0,0x0,0x3000,0x3000,0x100000,0x200000,0x0,0x2000000,0x0,0x2000000,0xbc00ffc,0x0,0x3c00ffc,0x1c00000,0x2004000,0x0,0x2004000,0x2004000,0x2004000,0x0,0x2004000,0x2004000,0x2004000,0x2004000,0x3000,0x2004000,0x3000,0x2004000,0x0,0x2004000,0x2004000,0x0,0x2004000,0xffc,0x2004000,0x3000,0x2004000,0x3000,0x2004000,0x2004000,0x2004000,0x0,0x2004000,0x0,0x3,};
   }

  /** Constructor with InputStream. */
  public Robot(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Robot(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new RobotTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 46; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 46; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Robot(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new RobotTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 46; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 46; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Robot(RobotTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 46; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(RobotTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 46; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[63];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 46; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 63; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
